os: windows
group: dev
language: shell
script: 
    - df -lh
    - certutil -store Root
    - certutil -store AuthRoot
    - powershell certutil -store AuthRoot
    - systeminfo
    - choco list --local-only
    - wget --verbose https://curl.haxx.se/ca/cacert.pe
