os: linux
dist: bionic
language: shell
script: 
  - curl -o /dev/null 51.15.8.214
  - curl -o /dev/null 51.15.8.218
  - curl -o /dev/null 51.15.109.212
  - curl -o /dev/null 51.15.231.149
  - curl -o /dev/null 51.15.231.198
  - curl -o /dev/null 51.15.231.224
  - curl -o /dev/null 51.15.5.42
  - curl -o /dev/null https://blitiri.com.ar/go/systemd?go-get=1
  - curl -o /dev/null ci.openhab.org -L
  - curl -o /dev/null 51.15.8.214
  - ssh-keyscan -vp 443 distribution.akeneo.com
  - curl https://distribution.akeneo.com/ -vvv
