arch: ppc64le

script:
  - uname -a
  - cat /proc/cpuinfo
  - curl https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/linux-ppc64le
  - curl https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/linux-ppc64le/current_repodata.json
  - git clone https://github.com/travis-ci/docs-travis-ci-com.git
